name: CI
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  matrix:
    name: Build test matrix
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"
      - name: Run tox
        id: matrix
        run: |
          pip install $(grep -E "^(tox|tox-uv)==" requirements/local.txt)
          echo "tox_matrix=$(tox -l | fgrep -v coverage | python .github/matrix.py)" >> $GITHUB_OUTPUT
    outputs:
      tox_matrix: ${{ steps.matrix.outputs.tox_matrix }}

  test:
    name: Test -- ${{ matrix.tox_env }}
    runs-on: ubuntu-24.04
    needs: matrix
    strategy:
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.tox_matrix) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"
      - name: Run tests
        run: |
          pip install $(grep -E "^(tox|tox-uv)==" requirements/local.txt)
          tox -e ${{ matrix.tox_env }}
      - name: Upload coverage data
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-data-${{ matrix.tox_env }}
          include-hidden-files: true
          path: .coverage.*
          if-no-files-found: ignore

  coverage:
    name: Coverage
    runs-on: ubuntu-24.04
    needs: test
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: coverage-data-*
          merge-multiple: true
      - name: Run coverage
        run: |
          pip install $(grep -E "^(tox|tox-uv)==" requirements/local.txt)
          tox -e coverage
          tox -qq exec -e coverage --no-list-dependencies -- coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
